site_name: Prompt Docs
site_url: https://acidicsoil.github.io/prompt-docs/
repo_url: https://github.com/AcidicSoil/prompt-docs
edit_uri: edit/main/docs

theme:
  name: material
  logo: assets/img/logo-32.svg
  custom_dir: overrides
  favicon: assets/img/favicon-32.ico
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home: index.md

  - Temp Prompts (organized):
      - 00 · Ideation:
          - Architecture:
              - "ADR – new": temp-prompts-organized/00-ideation/architecture/adr-new.architecture.md
              - Logging strategy: temp-prompts-organized/00-ideation/architecture/logging-strategy.architecture.md
              - Modular architecture: temp-prompts-organized/00-ideation/architecture/modular-architecture.architecture.md
              - Stack evaluation: temp-prompts-organized/00-ideation/architecture/stack-evaluation.architecture.md
          - Design:
              - Action diagram: temp-prompts-organized/00-ideation/design/action-diagram.design.md
              - API contract: temp-prompts-organized/00-ideation/design/api-contract.design.md
              - Design assets: temp-prompts-organized/00-ideation/design/design-assets.design.md
              - UI screenshots: temp-prompts-organized/00-ideation/design/ui-screenshots.design.md
          - Requirements:
              - Plan delta: temp-prompts-organized/00-ideation/requirements/plan-delta.requirements.md
              - Planning process: temp-prompts-organized/00-ideation/requirements/planning-process.requirements.md
              - PRD generator: temp-prompts-organized/00-ideation/requirements/prd-generator.requirements.md
              - Scope control: temp-prompts-organized/00-ideation/requirements/scope-control.requirements.md

      - 10 · Scaffold:
          - CI setup:
              - DevOps automation: temp-prompts-organized/10-scaffold/ci-setup/devops-automation.ci-setup.md
              - Env setup: temp-prompts-organized/10-scaffold/ci-setup/env-setup.ci-setup.md
              - Monitoring setup: temp-prompts-organized/10-scaffold/ci-setup/monitoring-setup.ci-setup.md
              - Secrets manager: temp-prompts-organized/10-scaffold/ci-setup/secrets-manager-setup.ci-setup.md
              - SLO setup: temp-prompts-organized/10-scaffold/ci-setup/slo-setup.ci-setup.md
          - Conventions:
              - Version control guide: temp-prompts-organized/10-scaffold/conventions/version-control-guide.conventions.md
          - Scaffold:
              - Auth: temp-prompts-organized/10-scaffold/scaffold/auth.scaffold.md
              - DB bootstrap: temp-prompts-organized/10-scaffold/scaffold/db-bootstrap.scaffold.md
              - Full-stack: temp-prompts-organized/10-scaffold/scaffold/fullstack.scaffold.md
              - IaC bootstrap: temp-prompts-organized/10-scaffold/scaffold/iac-bootstrap.scaffold.md

      - 20 · Implementation:
          - Impl:
              - Commit: temp-prompts-organized/20-implementation/impl/commit.impl.md
              - Content generation: temp-prompts-organized/20-implementation/impl/content-generation.impl.md
              - Feature flags: temp-prompts-organized/20-implementation/impl/feature-flags.impl.md
              - Fix: temp-prompts-organized/20-implementation/impl/fix.impl.md
              - Generate: temp-prompts-organized/20-implementation/impl/generate.impl.md
              - Prototype feature: temp-prompts-organized/20-implementation/impl/prototype-feature.impl.md
              - TODOs: temp-prompts-organized/20-implementation/impl/todos.impl.md
              - Voice input: temp-prompts-organized/20-implementation/impl/voice-input.impl.md
          - Review:
              - Audit: temp-prompts-organized/20-implementation/review/audit.review.md
              - Cross-check: temp-prompts-organized/20-implementation/review/cross-check.review.md
              - Evidence capture: temp-prompts-organized/20-implementation/review/evidence-capture.review.md
              - PR description: temp-prompts-organized/20-implementation/review/pr-desc.review.md
              - Review branch: temp-prompts-organized/20-implementation/review/review-branch.review.md
              - Review guide: temp-prompts-organized/20-implementation/review/review.review.md
              - TODO report: temp-prompts-organized/20-implementation/review/todo-report.review.md
              - TSConfig review: temp-prompts-organized/20-implementation/review/tsconfig-review.review.md
          - Spec-oriented:
              - Blame summary: temp-prompts-organized/20-implementation/spec-orient/blame-summary.spec-orient.md
              - Changed files: temp-prompts-organized/20-implementation/spec-orient/changed-files.spec-orient.md
              - Explain code: temp-prompts-organized/20-implementation/spec-orient/explain-code.spec-orient.md
              - Explain symbol: temp-prompts-organized/20-implementation/spec-orient/explain-symbol.spec-orient.md
              - Grep: temp-prompts-organized/20-implementation/spec-orient/grep.spec-orient.md
              - Research batch: temp-prompts-organized/20-implementation/spec-orient/research-batch.spec-orient.md
              - Research item: temp-prompts-organized/20-implementation/spec-orient/research-item.spec-orient.md

      - 30 · Refactor:
          - Perf:
              - Compare outputs: temp-prompts-organized/30-refactor/perf/compare-outputs.perf.md
              - Model evaluation: temp-prompts-organized/30-refactor/perf/model-evaluation.perf.md
              - Model strengths: temp-prompts-organized/30-refactor/perf/model-strengths.perf.md
          - Refactor:
              - ADR – new: temp-prompts-organized/30-refactor/refactor/adr-new.refactor.md
              - File modularity: temp-prompts-organized/30-refactor/refactor/file-modularity.refactor.md
              - Prettier adopt migration: temp-prompts-organized/30-refactor/refactor/prettier-adopt-migration-report.refactor.md
              - Refactor file: temp-prompts-organized/30-refactor/refactor/refactor-file.refactor.md
          - Refactor candidates:
              - Dead code scan: temp-prompts-organized/30-refactor/refactor-candidates/dead-code-scan.refactor-candidates.md
              - Migration plan: temp-prompts-organized/30-refactor/refactor-candidates/migration-plan.refactor-candidates.md
              - Suggestions: temp-prompts-organized/30-refactor/refactor-candidates/refactor-suggestions.refactor-candidates.md

      - 40 · Testing:
          - Coverage:
              - Guide: temp-prompts-organized/40-testing/coverage/guide.coverage.md
              - Regression guard: temp-prompts-organized/40-testing/coverage/regression-guard.coverage.md
          - Fix flakes:
              - Error analysis: temp-prompts-organized/40-testing/fix-flakes/error-analysis.fix-flakes.md
              - Explain failures: temp-prompts-organized/40-testing/fix-flakes/explain-failures.fix-flakes.md
          - Gen tests:
              - Check: temp-prompts-organized/40-testing/gen-tests/check.gen-tests.md
              - Integration test: temp-prompts-organized/40-testing/gen-tests/integration-test.gen-tests.md
          - Test plan:
              - E2E runner setup: temp-prompts-organized/40-testing/test-plan/e2e-runner-setup.test-plan.md
              - Query set: temp-prompts-organized/40-testing/test-plan/query-set.test-plan.md
              - Secrets scan: temp-prompts-organized/40-testing/test-plan/secrets-scan.test-plan.md

      - 50 · Docs:
          - API docs:
              - Local API docs: temp-prompts-organized/50-docs/api-docs/api-docs-local.api-docs.md
              - OpenAPI generate: temp-prompts-organized/50-docs/api-docs/openapi-generate.api-docs.md
          - Doc plan:
              - Gemini map: temp-prompts-organized/50-docs/doc-plan/gemini-map.doc-plan.md
              - Owners: temp-prompts-organized/50-docs/doc-plan/owners.doc-plan.md
          - Examples:
              - API usage: temp-prompts-organized/50-docs/examples/api-usage.examples.md
              - Reference implementation: temp-prompts-organized/50-docs/examples/reference-implementation.examples.md

      - 60 · Release:
          - Changelog:
              - From commits: temp-prompts-organized/60-release/changelog/from-commits.changelog.md
              - Project: temp-prompts-organized/60-release/changelog/project.changelog.md
              - Prepare notes: temp-prompts-organized/60-release/changelog/release-notes-prepare.changelog.md
              - Release notes: temp-prompts-organized/60-release/changelog/release-notes.changelog.md
              - Update: temp-prompts-organized/60-release/changelog/update.changelog.md
              - Verify: temp-prompts-organized/60-release/changelog/verify.changelog.md
          - Post-release checks:
              - Cleanup branches: temp-prompts-organized/60-release/post-release-checks/cleanup-branches.post-release-checks.md
              - License report: temp-prompts-organized/60-release/post-release-checks/license-report.post-release-checks.md
          - Versioning:
              - Version proposal: temp-prompts-organized/60-release/versioning/version-proposal.versioning.md

      - _Shared:
          - Rank root prompts: temp-prompts-organized/_shared/rank-root-prompts.shared.md
          - Reset strategy: temp-prompts-organized/_shared/reset-strategy.shared.md
          - Roll-up: temp-prompts-organized/_shared/roll-up.shared.md
          - Summary: temp-prompts-organized/_shared/summary.shared.md
          - Switch model: temp-prompts-organized/_shared/switch-model.shared.md
          - TM:
              - Advance: temp-prompts-organized/_shared/tm/advance.tm.md
              - Blockers: temp-prompts-organized/_shared/tm/blockers.tm.md
              - CI: temp-prompts-organized/_shared/tm/ci.tm.md
              - Delta: temp-prompts-organized/_shared/tm/delta.tm.md
              - Docs: temp-prompts-organized/_shared/tm/docs.tm.md
              - Next: temp-prompts-organized/_shared/tm/next.tm.md
              - Overview: temp-prompts-organized/_shared/tm/overview.tm.md
              - Refine: temp-prompts-organized/_shared/tm/refine.tm.md

      - _Templates:
          - Instruction file: temp-prompts-organized/_templates/instruction-file.templates.md
          - Prompt sequence generator: temp-prompts-organized/_templates/prompt-sequence-generator.templates.md
          - System-level instruction editor: temp-prompts-organized/_templates/system-level-instruction-editor.templates.md

      - Codefetch:
          - Codebase: temp-prompts-organized/codebase.md


  - Temp Prompts (refactored):
      - 3-step process (pre-refactor): temp-prompts-refactored/3-step-process-b4-refactoring.md
      - Prompt Optimizer: temp-prompts-refactored/Prompt-Optimizer.md
      - Action diagram: temp-prompts-refactored/action-diagram.md
      - ADR – new: temp-prompts-refactored/adr-new.md
      - ADR – new (refactor): temp-prompts-refactored/adr-new.refactor.md
      - API contract: temp-prompts-refactored/api-contract.md
      - API docs (local): temp-prompts-refactored/api-docs-local.md
      - API usage: temp-prompts-refactored/api-usage.md
      - Audit: temp-prompts-refactored/audit.md
      - Auth scaffold: temp-prompts-refactored/auth-scaffold.md
      - Blame summary: temp-prompts-refactored/blame-summary.md
      - Changed files: temp-prompts-refactored/changed-files.md
      - Changelog from commits: temp-prompts-refactored/changelog-from-commits.md
      - Changelog verify: temp-prompts-refactored/changelog-verify.md
      - Check: temp-prompts-refactored/check.md
      - Cleanup branches: temp-prompts-refactored/cleanup-branches.md
      - Commit msg: temp-prompts-refactored/commit-msg.md
      - Commit: temp-prompts-refactored/commit.md
      - Compare outputs: temp-prompts-refactored/compare-outputs.md
      - Content generation: temp-prompts-refactored/content-generation.md
      - Coverage guide: temp-prompts-refactored/coverage-guide.md
      - Cross-check: temp-prompts-refactored/cross-check.md
      - DB bootstrap: temp-prompts-refactored/db-bootstrap.md
      - Dead code scan: temp-prompts-refactored/dead-code-scan.md
      - Design assets: temp-prompts-refactored/design-assets.md
      - DevOps automation: temp-prompts-refactored/devops-automation.md
      - Docs fulfilled 100: temp-prompts-refactored/docs-fulfilled-100.md
      - E2E runner setup: temp-prompts-refactored/e2e-runner-setup.md
      - Env setup: temp-prompts-refactored/env-setup.md
      - Error analysis: temp-prompts-refactored/error-analysis.md
      - ESLint review: temp-prompts-refactored/eslint-review.md
      - Evidence capture: temp-prompts-refactored/evidence-capture.md
      - Explain code: temp-prompts-refactored/explain-code.md
      - Explain failures: temp-prompts-refactored/explain-failures.md
      - Explain symbol: temp-prompts-refactored/explain-symbol.md
      - Feature flags: temp-prompts-refactored/feature-flags.md
      - File modularity: temp-prompts-refactored/file-modularity.md
      - Fix: temp-prompts-refactored/fix.md
      - Gemini map: temp-prompts-refactored/gemini-map.md
      - Generate README: temp-prompts-refactored/generate-readme.md
      - Generate: temp-prompts-refactored/generate.md
      - Grep: temp-prompts-refactored/grep.md
      - IaC bootstrap: temp-prompts-refactored/iac-bootstrap.md
      - Instruction file: temp-prompts-refactored/instruction-file.md
      - Integration test: temp-prompts-refactored/integration-test.md
      - License report: temp-prompts-refactored/license-report.md
      - Logging strategy: temp-prompts-refactored/logging-strategy.md
      - Migration plan: temp-prompts-refactored/migration-plan.md
      - Missing docs: temp-prompts-refactored/missing-docs.md
      - Model evaluation: temp-prompts-refactored/model-evaluation.md
      - Model strengths: temp-prompts-refactored/model-strengths.md
      - Modular architecture: temp-prompts-refactored/modular-architecture.md
      - Monitoring setup: temp-prompts-refactored/monitoring-setup.md
      - OpenAPI generate: temp-prompts-refactored/openapi-generate.md
      - Owners: temp-prompts-refactored/owners.md
      - Plan delta: temp-prompts-refactored/plan-delta.md
      - Planning process: temp-prompts-refactored/planning-process.md
      - PR desc: temp-prompts-refactored/pr-desc.md
      - PRD generator: temp-prompts-refactored/prd-generator.md
      - Prettier migration report: temp-prompts-refactored/prettier-adopt_Migration_report.md
      - Problem analyzer: temp-prompts-refactored/problem-analyzer.md
      - Prompt sequence generator: temp-prompts-refactored/prompt-sequence-generator.md
      - Prototype feature: temp-prompts-refactored/prototype-feature.md
      - Query set: temp-prompts-refactored/query-set.md
      - Rank root prompts: temp-prompts-refactored/rank-root-prompts.md
      - Refactor file: temp-prompts-refactored/refactor-file.md
      - Refactor suggestions: temp-prompts-refactored/refactor-suggestions.md
      - Reference implementation: temp-prompts-refactored/reference-implementation.md
      - Regression guard: temp-prompts-refactored/regression-guard.md
      - Release notes prepare: temp-prompts-refactored/release-notes-prepare.md
      - Release notes: temp-prompts-refactored/release-notes.md
      - Research batch: temp-prompts-refactored/research-batch.md
      - Research item: temp-prompts-refactored/research-item.md
      - Reset strategy: temp-prompts-refactored/reset-strategy.md
      - Review branch: temp-prompts-refactored/review-branch.md
      - Review: temp-prompts-refactored/review.md
      - Roll-up: temp-prompts-refactored/roll-up.md
      - Scaffold (full-stack): temp-prompts-refactored/scaffold-fullstack.md
      - Scope control: temp-prompts-refactored/scope-control.md
      - Secrets manager setup: temp-prompts-refactored/secrets-manager-setup.md
      - Secrets scan: temp-prompts-refactored/secrets-scan.md
      - SLO setup: temp-prompts-refactored/slo-setup.md
      - Stack evaluation: temp-prompts-refactored/stack-evaluation.md
      - Stop guessing: temp-prompts-refactored/stop-guessing.md
      - Summary 1: temp-prompts-refactored/summary-1.md
      - Summary 2: temp-prompts-refactored/summary-2.md
      - Summary: temp-prompts-refactored/summary.md
      - Switch model: temp-prompts-refactored/switch-model.md
      - System-level instruction editor: temp-prompts-refactored/system-level-instruction-editor.md
      - TM · advance: temp-prompts-refactored/tm-advance.md
      - TM · blockers: temp-prompts-refactored/tm-blockers.md
      - TM · CI: temp-prompts-refactored/tm-ci.md
      - TM · delta: temp-prompts-refactored/tm-delta.md
      - TM · docs: temp-prompts-refactored/tm-docs.md
      - TM · next: temp-prompts-refactored/tm-next.md
      - TM · overview: temp-prompts-refactored/tm-overview.md
      - TM · refine: temp-prompts-refactored/tm-refine.md
      - TODO report: temp-prompts-refactored/todo-report.md
      - TODOs: temp-prompts-refactored/todos.md
      - TSConfig review: temp-prompts-refactored/tsconfig-review.md
      - UI screenshots: temp-prompts-refactored/ui-screenshots.md
      - Update changelog: temp-prompts-refactored/update-changelog.md
      - Version control guide: temp-prompts-refactored/version-control-guide.md
      - Version proposal: temp-prompts-refactored/version-proposal.md
      - Voice input: temp-prompts-refactored/voice-input.md

